spring:
  application:
    name: conjur-service
  cloud:
    config:
      uri: http://localhost:8888
      import: "optional:configserver:${CONFIG_SERVER:http://localhost:8888}"
  config:
    import: "optional:configserver:${CONFIG_SERVER:http://localhost:8888}"
